name: Build, package and release clang+llvm
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  Auxiliary:
    strategy:
      matrix:
        instance: [0, 1, 2, 3, 4]
      fail-fast: true
    uses: ./.github/workflows/auxiliary.yml
    secrets: inherit
    with:
      job-index: ${{ strategy.job-index }}
      job-total: ${{ strategy.job-total }}
  Primary:
    strategy:
      fail-fast: true
    uses: ./.github/workflows/primary.yml
    secrets: inherit
    with:
      arch: "arm64"
      os:  "macos-15"
      auxiliary_count: "5"
